# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: test v2

on:
  push:
    paths:
    - '**.js'
    branches: [ master ]
  workflow_dispatch:
  # pull_request:
  #   paths:
  #   - '**.js'
  #   branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: CI
      run: npm ci

    - name: Build
      run: npm run build --if-present

    - name: ESlint
      run: npm run test:lint

    - name: Tests
      run: npm test
      env:
        HYPIXEL_KEY: '12345678-1234-1234-1234-123456789abc'
        HYPIXEL_API_ENDPOINT: 'http://localhost:3000/'
